import type { WeddingData } from "@/types/wedding";
import { GUESTBOOK_MESSAGE_MAX, GUESTBOOK_NAME_MAX } from "@/types/guestbook";

export type {
  Couple,
  GalleryImage,
  GiftPerson,
  InvitationCopy,
  NavigationItem,
  ParentNames,
  PersonProfile,
  SeoConfig,
  WeddingCover,
  WeddingData,
  WeddingDate,
  WeddingDetails,
  WeddingEvent,
  WeddingEventType,
  WeddingGift,
  WeddingTimeline,
  WeddingTimelineIcon,
  WeddingTimelineItem,
  WeddingVenue,
} from "@/types/wedding";

/**
 * Single source of truth for static wedding content.
 * UI components must import from `@/config/weddingData` only.
 * Guestbook wishes are persisted in Supabase and must not live here.
 */
export const weddingData: WeddingData = {
  couple: {
    bride: {
      name: "Yến Vy",
      fullName: "Nguyễn Yến Vy",
      photo: "/images/couple/bride.jpg",
      parents: {
        father: "Nguyễn Ngọc Sỹ",
        mother: "Nguyễn Thị Hồng",
      },
      description:
        "Dịu dàng, chân thành và luôn trân quý những điều giản dị. Với em, hạnh phúc là khi tìm thấy một người để cùng sẻ chia những ngày bình thường nhất.",
      quote: "Gặp anh, em biết mình đã về đúng nhà.",
    },
    groom: {
      name: "Nhật Song",
      fullName: "Nguyễn Nhật Song",
      photo: "/images/couple/groom.jpg",
      parents: {
        father: "Nguyễn Văn Thành",
        mother: "Ngô Thị Phần",
      },
      description:
        "Điềm đạm, chân thành và luôn tin rằng tình yêu đẹp nhất là sự đồng hành. Với anh, hạnh phúc là có một người để thương, để sẻ chia và cùng nhau đi qua những năm tháng phía trước.",
      quote: "Từ ngày có em, anh biết mình muốn trở về đâu.",
    },
  },

  wedding: {
    title: "Lễ Thành Hôn",
    phrase: "Từ đây, hai ta một nhà.",
    timezone: "Asia/Ho_Chi_Minh",
    date: {
      iso: "2026-12-20",
      display: "20.12.2026",
      day: "20",
      month: "12",
      year: "2026",
    },
    venue: {
      name: "Trung tâm Tiệc cưới Riverside Palace",
      address: "360D Bến Vân Đồn, Phường Khánh Hội, TP. Hồ Chí Minh",
      mapsUrl:
        "https://www.google.com/maps/search/?api=1&query=Trung+tâm+Tiệc+cưới+Riverside+Palace+360D+Bến+Vân+Đồn+Phường+Khánh+Hội+Hồ+Chí+Minh",
    },
    cover: {
      desktopImage: "/images/hero/hero-desktop.jpg",
      mobileImage: "/images/hero/hero-mobile.jpg",
    },
    calendarDurationHours: 2,
  },

  events: [
    {
      id: "event-bride",
      type: "bride",
      title: "Lễ Vu Quy",
      date: "2026-12-20",
      time: "08:00",
      venue: "Tư gia Nhà Gái",
      address: "Khối 4, phường Thu Thủy, Thị xã Cửa Lò, Nghệ An",
      dressCode: "Trang phục lịch sự",
      mapsUrl: "https://maps.app.goo.gl/G2iF34AjVL2foCW36",
    },
    {
      id: "event-groom",
      type: "groom",
      title: "Lễ Thành Hôn",
      date: "2026-12-22",
      time: "10:30",
      venue: "Tư gia Nhà Trai",
      address: "Diễn Châu, Nghệ An",
      dressCode: "Trang phục lịch sự",
      mapsUrl: "https://maps.app.goo.gl/G2iF34AjVL2foCW36",
    },
  ],

  timeline: {
    title: "Timeline",
    subtitle:
      "Cùng chúng mình lưu giữ những khoảnh khắc đáng nhớ trong ngày đặc biệt này.",
    backgroundImage: "/images/timeline/timeline-bg.webp",
    backgroundAlt: "Không gian tiệc cưới với hoa và thiệp cưới",
    items: [
      {
        id: "ceremony",
        time: "15:00",
        title: "Thánh lễ",
        description: "Thánh lễ hôn phối",
        icon: "church",
      },
      {
        id: "welcome",
        time: "17:00",
        title: "Đón khách",
        description: "Hân hoan đón khách",
        icon: "camera",
      },
      {
        id: "dinner",
        time: "18:00",
        title: "Khai tiệc",
        description: "Cùng nâng ly & chung vui",
        icon: "utensils",
      },
      {
        id: "party",
        time: "19:00",
        title: "Chung vui",
        description: "Minigame & khiêu vũ",
        icon: "party",
      },
    ],
  },

  gallery: [
    {
      id: "gallery-01",
      src: "/images/gallery/gallery-01.jpg",
      alt: "Yến Vy và Nhật Song trong khoảnh khắc nhìn nhau dịu dàng",
      width: 1200,
      height: 1600,
    },
    {
      id: "gallery-02",
      src: "/images/gallery/gallery-02.jpg",
      alt: "Chân dung cô dâu Yến Vy trong ánh sáng buổi chiều",
      width: 1200,
      height: 1500,
    },
    {
      id: "gallery-03",
      src: "/images/gallery/gallery-03.jpg",
      alt: "Chú rể Nhật Song trong trang phục lễ cưới",
      width: 1200,
      height: 1500,
    },
    {
      id: "gallery-04",
      src: "/images/gallery/gallery-04.jpg",
      alt: "Hai bạn nắm tay nhau bước trên lối đi rợp hoa",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-05",
      src: "/images/gallery/gallery-05.jpg",
      alt: "Khoảnh khắc trao lời thề nguyện giữa Yến Vy và Nhật Song",
      width: 1400,
      height: 1600,
    },
    {
      id: "gallery-06",
      src: "/images/gallery/gallery-06.jpg",
      alt: "Chân dung đôi uyên ương bên hoa tươi và ánh nến",
      width: 1200,
      height: 1600,
    },
    {
      id: "gallery-07",
      src: "/images/gallery/gallery-07.jpg",
      alt: "Yến Vy cười trong vòng tay Nhật Song",
      width: 1600,
      height: 1100,
    },
    {
      id: "gallery-08",
      src: "/images/gallery/gallery-08.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-09",
      src: "/images/gallery/gallery-09.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-10",
      src: "/images/gallery/gallery-10.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-11",
      src: "/images/gallery/gallery-11.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-12",
      src: "/images/gallery/gallery-12.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-13",
      src: "/images/gallery/gallery-13.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-14",
      src: "/images/gallery/gallery-14.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-15",
      src: "/images/gallery/gallery-15.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-16",
      src: "/images/gallery/gallery-16.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-17",
      src: "/images/gallery/gallery-17.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-18",
      src: "/images/gallery/gallery-18.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
    {
      id: "gallery-19",
      src: "/images/gallery/gallery-19.jpg",
      alt: "Bức ảnh lưu niệm ngày Lễ Thành Hôn 20.12.2026",
      width: 1600,
      height: 1200,
    },
  ],

  gifts: [
    {
      id: "gift-bride",
      person: "bride",
      name: "Nguyễn Yến Vy",
      bankName: "Vietinbank",
      accountNumber: "100872095048",
      accountName: "NGUYEN YEN VY",
      qrImage: "/images/gift/bride-qr.png",
      transferNote: "Mung cuoi Yen Vy",
    },
    {
      id: "gift-groom",
      person: "groom",
      name: "Nguyễn Nhật Song",
      bankName: "Vietinbank",
      accountNumber: "100872095048",
      accountName: "NGUYEN NHAT SONG",
      qrImage: "/images/gift/groom-qr.png",
      transferNote: "Mung cuoi Nhat Song",
    },
  ],

  navigation: [
    { id: "home", label: "Trang chủ", href: "#home" },
    { id: "story", label: "Câu chuyện", href: "#story" },
    { id: "save-the-date", label: "Ngày cưới", href: "#save-the-date" },
    { id: "events", label: "Sự kiện", href: "#events" },
    { id: "timeline", label: "Timeline", href: "#timeline" },
    { id: "gallery", label: "Album", href: "#gallery" },
    { id: "guestbook", label: "Lời chúc", href: "#guestbook" },
    { id: "gift", label: "Mừng cưới", href: "#gift" },
  ],

  seo: {
    title: "Đám Cưới Yến Vy & Nhật Song | 20.12.2026",
    description:
      "Trân trọng kính mời bạn đến chung vui trong ngày cưới của Yến Vy và Nhật Song vào ngày 20 tháng 12 năm 2026.",
    keywords: [
      "Yến Vy",
      "Nhật Song",
      "đám cưới",
      "thiệp cưới",
      "wedding invitation",
      "20.12.2026",
    ],
    ogImage: "/images/og-image.jpg",
    ogTitle: "Yến Vy & Nhật Song",
    ogDescription: "Save the Date — 20.12.2026",
    canonicalUrl: "",
    language: "vi",
    locale: "vi_VN",
    favicon: "/favicon.ico",
    appleIcon: "/apple-touch-icon.png",
  },

  copy: {
    skipToContent: "Tới nội dung thiệp",
    saveTheDate: {
      title: "Save the Date",
      description:
        "Hãy dành ngày này để cùng chúng mình lưu giữ một kỷ niệm thật đẹp.",
      countdownDays: "Ngày",
      countdownHours: "Giờ",
      countdownMinutes: "Phút",
      countdownSeconds: "Giây",
      addToCalendarPrefix: "Tải lịch: ",
    },
    guestbook: {
      title: "Lời chúc",
      description:
        "Mời bạn viết vài lời chân thành vào sổ cưới của chúng mình.",
      nameLabel: "Họ và tên",
      messageLabel: "Lời chúc",
      namePlaceholder: "Họ và tên của bạn",
      messagePlaceholder: "Viết lời chúc phúc...",
      nameRequired: "Vui lòng nhập họ và tên.",
      nameTooLong: `Họ và tên tối đa ${GUESTBOOK_NAME_MAX} ký tự.`,
      messageRequired: "Vui lòng viết lời chúc.",
      messageTooLong: `Lời chúc tối đa ${GUESTBOOK_MESSAGE_MAX} ký tự.`,
      submitLabel: "Gửi lời chúc",
      submittingLabel: "Đang ghi vào sổ...",
      successMessage: "Lời chúc đã được ghi vào sổ. Cảm ơn bạn.",
      errorMessage: "Chưa gửi được lời chúc. Vui lòng thử lại sau.",
      rateLimitMessage: "Bạn gửi hơi nhanh. Vui lòng thử lại sau một lát.",
      listLoading: "Đang mở sổ lưu bút...",
      listEmpty: "Sổ còn đang trống. Hãy là người đầu tiên viết lời chúc.",
      listError: "Không mở được sổ lời chúc lúc này.",
      listRetry: "Thử mở lại",
      listTitle: "Những lời đã ghi",
    },
    gift: {
      title: "Mừng cưới",
      description:
        "Nếu muốn gửi một món quà nhỏ, xin chuyển khoản theo thông tin dưới đây.",
      bank: "Ngân hàng",
      accountName: "Chủ tài khoản",
      accountNumber: "Số tài khoản",
      transferNote: "Nội dung chuyển khoản",
      copy: "Sao chép số tài khoản",
      copied: "Đã sao chép số tài khoản.",
      copyFailed: "Không sao chép được. Vui lòng chọn số tài khoản.",
      brideRole: "Cô dâu",
      groomRole: "Chú rể",
    },
    events: {
      mapsLabel: "Xem bản đồ",
      mapsNewTab: " (mở tab mới)",
      typeBride: "Nhà gái",
      typeGroom: "Nhà trai",
      typeCeremony: "Lễ cưới",
      typeReception: "Tiệc cưới",
    },
    gallery: {
      close: "Đóng album",
      previous: "Ảnh trước",
      next: "Ảnh tiếp",
      openLabeled: "Xem ảnh lớn: ",
      openIndexed: "Xem ảnh lớn ",
    },
    thankYou: {
      title: "Thank You",
      message:
        "Cảm ơn bạn đã dành thời gian hiện diện, chứng kiến và sẻ chia niềm vui trong ngày đặc biệt của chúng mình.",
      image: "/images/thank-you/thank-you.jpg",
      imageAlt: "Yến Vy và Nhật Song trong ngày cưới",
    },
  },
};
